### PR TITLE
[IA-3326] Add Lifesciences API Runner Role

### PR DESCRIPTION
**Pull request by gpcarr**
plan on running the script to update custom roles manually per environment starting with test.firecloud.org with Andrew from CI early next week

### CODE REVIEW

**Review by Qi77Qi — APPROVED** [review]
:shipit:

**Review by dvoet — CHANGES_REQUESTED** [review]
I don't think we should add these permissions to this role. This affects all workspaces. It may be ok to grant these permissions in some workspaces but blanket adding for all inhibits our ability implement policies that prevent these permission in some. Perhaps [deny policies](https://cloud.google.com/iam/docs/deny-access) could be used but they are not GA yet. Instead, perhaps there could be an explicit "enable nextflow" api for a workspace that would setup the right permissions.

Looking at the [AoU design doc](https://docs.google.com/document/d/1mlbesp3IIO5tO0d_l_ZFnwKQC_No68TeHSBAQGSGwcM/edit#heading=h.fawyt7ahei1), they were planning to grant the role only to the pet SA in the workspace's project.

**Comment by dvoet** [comment]
Another approach would be to automatically add `roles/lifesciences.workflowsRunner` to the project for the can compute policy when creating a workspace in rawls. In the future we can make the decision about whether or not to do this based on policy. Keeping it separate from `terra_workspace_can_compute` custom role gives us this flexibility.

**Comment by gpcarr** [comment]
> Another approach would be to automatically add `roles/lifesciences.workflowsRunner` to the project for the can compute policy when creating a workspace in rawls. In the future we can make the decision about whether or not to do this based on policy. Keeping it separate from `terra_workspace_can_compute` custom role gives us this flexibility.

HI @dvoet - if I understand correctly, it seems like adding this to rawls may be the best path forward. That way only newly created projects will have the `roles/lifesciences.workflowsRunner` role and we keep it separate from `terra_workspace_can_compute` which we're eventually looking to migrate to terraform-ap. I'll take a look at rawls and get started on this and like you said - we can revisit doing this based on policy in the future

**Comment by gpcarr** [comment]
Hi @dvoet - we ended up going with the custom iam role approach (https://github.com/broadinstitute/terraform-terra/pull/164 - i'll be closing this PR, forgot i had opened this as well) we only created the role using this [script](https://github.com/broadinstitute/terraform-terra/blob/master/scripts/project-setup-scripts/create-custom-iam-roles-for-projects.sh) and did not backfill existing projects. i plan on adding this custom role to rawls now and that's in this [PR](https://github.com/broadinstitute/rawls/pull/1753/files) - still working on that change. so this nextflow role will still be separate from the custom canCompute role and will only apply to new projects

**Pull request closed without merging**
