### PR TITLE
Enable AoU log sinks in terra prod

### PR DESCRIPTION
**Pull request by calbach**
Permissions should now be correctly configured.

### CODE REVIEW

**Comment by calbach** [comment]
Just saw @gmalkov is out. @dvoet would you be able to apply this? and https://github.com/broadinstitute/terraform-terra/pull/134 ?

**Comment by calbach** [comment]
or maybe @emandakh ?

**Comment by emandakh** [comment]
@gmalkov should look at it first, he will be back tomorrow.

**Comment by calbach** [comment]
Ah OK - thanks, tomorrow's fine.

**Pull request merged**
